# Generated by Django 5.0.4 on 2024-05-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gemini', '0002_delete_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.CharField(max_length=200)),
                ('respuesta', models.CharField(max_length=200)),
            ],
        ),
    ]
